apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
  labels:
    pv-usage: backup
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/pv-backup/