apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    pv-usage: mysql
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/pv0001/